module.exports = {
	searchControlDivId: 'searchControl',
	orgLatitude: 49.764775,
	orgLongitude: -85.323214,
	orgzoomLevel: 5,
	defaultMapTypeId: google.maps.MapTypeId.ROADMAP,
	mapCanvasDivId: 'map_canvas',
	isCoordinatesVisible: true,
	coordinatesDivId: 'coordinates',
	minMapScale: 5,
	maxMapScale: 21,
	disallowMouseClick: false,
	searchInputBoxDivId: 'map_query',
	informationDivId: 'information',
	maxQueryZoomLevel: 17,
	maxQueryReturn: 500,
	queryTableDivId: 'query_table',
	otherInfoDivId: 'otherInfo',
	otherInfoHTML: '',
	infoWindowWidth: '280px',
	infoWindowHeight: '200px',
	infoWindowContentHeight: '160px',
	infoWindowContentWidth: '240px'
};