module.exports = {
	searchControlDivId: 'searchControl',
	orgLatitude: 49.764775,
	orgLongitude: -85.323214,
	orgzoomLevel: 5,
	defaultMapTypeId: google.maps.MapTypeId.ROADMAP,
	mapCanvasDivId: 'map_canvas',
	isCoordinatesVisible: true,
	coordinatesDivId: 'coordinates',
	minMapScale: 5,
	maxMapScale: 21,
	disallowMouseClick: false,
	searchInputBoxDivId: 'map_query',
	searchRadiusDivId: 'lstRadius',
	informationDivId: 'information',
	maxQueryZoomLevel: 17,
	maxQueryReturn: 500,
	queryTableDivId: 'query_table',
	otherInfoDivId: 'otherInfo',
	otherInfoHTML: '',
	infoWindowWidth: '280px',
	infoWindowHeight: '200px',
	infoWindowContentHeight: '160px',
	infoWindowContentWidth: '240px',
	dynamicResourcesLoadingURL: 'http://files.ontariogovernment.ca/moe_mapping/mapping/js/MOEMap/',
	legendAvailable: false,	
	legendURL: 'legend.png', 
	legendSize: {width: 270, height: 81},
	legendLocation: {ratioX: 0.01, ratioY: 0.25},

	pointBufferToolAvailable: false,
	pointBufferToolUpIcon: 'Bptu.png',
	pointBufferToolDownIcon: 'Bptd.png',
	pointBufferToolSize: {width: 31, height: 31},
	pointBufferToolLocation: {ratioX: 0.12, ratioY: 0.98},
	pointBufferToolCircle: {color: '#FF0000', opacity: 1, weight: 2},
	refreshInterval: 500
};